2024-11-06 01:45:55.435 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:45:55.436 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:45:55.437 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 01:45:55.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:45:55.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:45:55.437 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 01:45:55.438 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 01:45:55.438 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 01:45:55.438 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 01:45:55.438 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:45:55.438 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:45:55.439 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 01:45:55.439 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 01:45:55.439 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 01:48:20.529 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:48:20.530 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:48:20.531 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 01:48:20.531 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:48:20.531 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:48:20.531 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 01:48:20.531 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 01:48:20.532 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 01:48:20.532 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 01:48:20.532 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:48:20.532 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:48:20.533 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 01:48:20.533 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 01:48:20.533 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 01:48:20.533 | ERROR    | app.services.user_service:create_user:29 - Exception occured: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x0000029C0B674860>
    └ <WorkerThread(AnyIO worker thread, started 20180)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x0000029C10EC7B00>
    └ <WorkerThread(AnyIO worker thread, started 20180)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x0000029C10E753A0>, db=<sqlalchemy.orm.session.Session object at 0x0000029C10EB88...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x0000029C10EB89C0>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 36, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First23', email='firstUser23@gmail.com', password='Password1234$', role=None)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x0000029C10EB8850>
           │             └ <function create_user at 0x0000029C0FB2D9E0>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 16, in create_user
    user_validator.validate_role(user.role.value)
    │              │             │    └ None
    │              │             └ UserCreate(username='First23', email='firstUser23@gmail.com', password='Password1234$', role=None)
    │              └ <function validate_role at 0x0000029C0FB2E3E0>
    └ <module 'app.validators.user_validator' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\val...

AttributeError: 'NoneType' object has no attribute 'value'
2024-11-06 01:50:58.085 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:50:58.087 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:50:58.087 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 01:50:58.087 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:50:58.087 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:50:58.088 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 01:50:58.088 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 01:50:58.088 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 01:50:58.088 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 01:50:58.089 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:50:58.089 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:50:58.089 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 01:50:58.090 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 01:50:58.090 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 01:50:58.090 | ERROR    | app.services.user_service:create_user:30 - Exception occured: 'NoneType' object has no attribute 'value'
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002C9B1834860>
    └ <WorkerThread(AnyIO worker thread, started 26164)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x000002C9B707BB00>
    └ <WorkerThread(AnyIO worker thread, started 26164)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x000002C9B70253A0>, db=<sqlalchemy.orm.session.Session object at 0x000002C9B7063A...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x000002C9B7021780>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 36, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First23', email='firstUser23@gmail.com', password='Password1234$', role=None)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x000002C9B7063A10>
           │             └ <function create_user at 0x000002C9B5CDD9E0>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 16, in create_user
    print(user.role.value)
          │    └ None
          └ UserCreate(username='First23', email='firstUser23@gmail.com', password='Password1234$', role=None)

AttributeError: 'NoneType' object has no attribute 'value'
2024-11-06 01:52:09.093 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:52:09.095 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:52:09.095 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 01:52:09.095 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:52:09.096 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:52:09.096 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 01:52:09.096 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 01:52:09.096 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 01:52:09.096 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 01:52:09.096 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 01:52:09.097 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 01:52:09.097 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 01:52:09.097 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 01:52:09.097 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 01:52:09.120 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First23
2024-11-06 01:52:09.125 | INFO     | app.crud.user:get_by_username_email_id:23 - Searching for user by email: firstUser23@gmail.com
2024-11-06 01:52:09.126 | INFO     | app.crud.user:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 01:52:09.126 | INFO     | app.crud.user:create:53 - Attempting to create user with username=First23, email=firstUser23@gmail.com
2024-11-06 01:52:09.133 | INFO     | app.crud.user:create:70 - User created successfully with username=First23, email=firstUser23@gmail.com
2024-11-06 02:01:58.821 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:01:58.822 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:01:58.822 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:01:58.823 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:01:58.823 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:01:58.823 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:01:58.823 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:01:58.824 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:01:58.824 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:01:58.824 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:01:58.824 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:01:58.825 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:01:58.825 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:01:58.825 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:01:58.826 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:01:58.826 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:01:58.826 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:01:58.826 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:01:58.849 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:01:58.855 | INFO     | app.crud.user:get_by_username_email_id:23 - Searching for user by email: firstUser24@gmail.com
2024-11-06 02:01:58.857 | INFO     | app.crud.user:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:01:58.858 | INFO     | app.crud.user:create:53 - Attempting to create user with username=First24, email=firstUser24@gmail.com
2024-11-06 02:01:58.862 | INFO     | app.crud.user:create:70 - User created successfully with username=First24, email=firstUser24@gmail.com
2024-11-06 02:05:18.420 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:18.421 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:18.421 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:05:18.421 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:18.422 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:18.422 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:05:18.422 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:05:18.423 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:05:18.423 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:05:18.423 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:18.423 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:18.424 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:05:18.424 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:05:18.424 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:05:18.424 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:05:18.424 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:18.425 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:18.425 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:05:18.446 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:05:18.455 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:05:54.646 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:54.647 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:54.648 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:05:54.648 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:54.648 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:54.648 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:05:54.648 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:05:54.649 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:05:54.649 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:05:54.649 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:54.649 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:54.649 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:05:54.649 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:05:54.650 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:05:54.650 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:05:54.650 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:05:54.650 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:05:54.650 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:05:54.674 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:05:54.678 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:05:54.678 | ERROR    | app.services.user_service:create_user:31 - Exception occured: 409: Username or email already in use
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002B6909D4860>
    └ <WorkerThread(AnyIO worker thread, started 28572)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x000002B696217BA0>
    └ <WorkerThread(AnyIO worker thread, started 28572)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x000002B6961C53A0>, db=<sqlalchemy.orm.session.Session object at 0x000002B6962025...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x000002B696269440>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 37, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First24', email='firstUser24@gmail.com', password='Password1234$', role=<UserRole.admin: 'admin'>)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x000002B696202550>
           │             └ <function create_user at 0x000002B694E7D9E0>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 25, in create_user
    raise HTTPException(status_code=409, detail="Username or email already in use")
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 409: Username or email already in use
2024-11-06 02:06:49.751 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:06:49.752 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:06:49.752 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:06:49.752 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:06:49.752 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:06:49.752 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:06:49.753 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:06:49.753 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:06:49.753 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:06:49.753 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:06:49.753 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:06:49.754 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:06:49.754 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:06:49.754 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:06:49.755 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:06:49.755 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:06:49.755 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:06:49.755 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:06:49.782 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:06:49.786 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:06:49.787 | ERROR    | app.services.user_service:create_user:31 - Exception occured: 411: Username or email already in use
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000281AEBF4860>
    └ <WorkerThread(AnyIO worker thread, started 21820)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x00000281B43C7BA0>
    └ <WorkerThread(AnyIO worker thread, started 21820)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x00000281B43753A0>, db=<sqlalchemy.orm.session.Session object at 0x00000281B30007...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x00000281B43A25C0>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 37, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First24', email='firstUser24@gmail.com', password='Password1234$', role=<UserRole.admin: 'admin'>)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x00000281B3000750>
           │             └ <function create_user at 0x00000281B302D940>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 25, in create_user
    raise HTTPException(status_code=411, detail="Username or email already in use")
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 411: Username or email already in use
2024-11-06 02:08:57.320 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:08:57.322 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:08:57.322 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:08:57.322 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:08:57.322 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:08:57.322 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:08:57.323 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:08:57.323 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:08:57.323 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:08:57.323 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:08:57.323 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:08:57.323 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:08:57.324 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:08:57.324 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:08:57.324 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:08:57.324 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:08:57.324 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:08:57.324 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:08:57.347 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:08:57.351 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:08:57.352 | ERROR    | app.services.user_service:create_user:31 - Exception occured: 409: Username or email already in use
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x00000263AB574860>
    └ <WorkerThread(AnyIO worker thread, started 9816)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x00000263B0DB7BA0>
    └ <WorkerThread(AnyIO worker thread, started 9816)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x00000263B0D653A0>, db=<sqlalchemy.orm.session.Session object at 0x00000263B0DA3A...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x00000263B0DA8CC0>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 37, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First24', email='firstUser24@gmail.com', password='Password1234$', role=<UserRole.admin: 'admin'>)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x00000263B0DA3A10>
           │             └ <function create_user at 0x00000263AFA1D940>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 25, in create_user
    raise HTTPException(status_code=409, detail="Username or email already in use")
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 409: Username or email already in use
2024-11-06 02:09:47.484 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:09:47.485 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:09:47.486 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:09:47.486 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:09:47.486 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:09:47.486 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:09:47.486 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:09:47.486 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:09:47.486 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:09:47.486 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:09:47.487 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:09:47.487 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:09:47.487 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:09:47.488 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:09:47.488 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:09:47.488 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:09:47.488 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:09:47.488 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:09:47.512 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:09:47.517 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:10:21.188 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:10:21.189 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:10:21.189 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:10:21.189 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:10:21.189 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:10:21.190 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:10:21.190 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:10:21.190 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:10:21.190 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:10:21.190 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:10:21.190 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:10:21.191 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:10:21.191 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:10:21.191 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:10:21.191 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:10:21.191 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:10:21.191 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:10:21.192 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:10:21.214 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:10:21.220 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:10:21.220 | ERROR    | app.services.user_service:create_user:31 - Exception occured: 409: Username or email already in use
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000001CF24684860>
    └ <WorkerThread(AnyIO worker thread, started 4556)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x000001CF29ED7BA0>
    └ <WorkerThread(AnyIO worker thread, started 4556)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x000001CF29E853A0>, db=<sqlalchemy.orm.session.Session object at 0x000001CF29EDB3...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x000001CF29E96C40>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 37, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First24', email='firstUser24@gmail.com', password='Password1234$', role=<UserRole.admin: 'admin'>)
           │             │              └ <sqlalchemy.orm.session.Session object at 0x000001CF29EDB310>
           │             └ <function create_user at 0x000001CF28B3D940>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 25, in create_user
    raise HTTPException(status_code=409, detail="Username or email already in use")
          └ <class 'fastapi.exceptions.HTTPException'>

fastapi.exceptions.HTTPException: 409: Username or email already in use
2024-11-06 02:11:14.313 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:11:14.314 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:11:14.314 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:11:14.314 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:11:14.315 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:11:14.315 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:11:14.315 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:11:14.315 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:11:14.316 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:11:14.316 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:11:14.316 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:11:14.316 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:11:14.316 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:11:14.318 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:11:14.318 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:11:14.318 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:11:14.318 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:11:14.319 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:11:14.340 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:11:14.345 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:16:03.017 | INFO     | app.services.user_service:create_user:11 - CREATING USER ACCOUNT
2024-11-06 02:16:03.018 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:16:03.018 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:16:03.018 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:16:03.018 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:16:03.019 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:16:03.019 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:16:03.019 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:16:03.019 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:16:03.019 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:16:03.019 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:16:03.021 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:16:03.021 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:16:03.021 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:16:03.021 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:16:03.021 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:16:03.022 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:16:03.022 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:16:03.022 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:16:03.043 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First24
2024-11-06 02:16:03.048 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First24
2024-11-06 02:16:03.049 | WARNING  | app.services.user_service:create_user:25 - USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:17:08.255 | INFO     | app.services.user_service:create_user:11 - CREATING USER ACCOUNT
2024-11-06 02:17:08.256 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:17:08.256 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:17:08.257 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:17:08.257 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:17:08.257 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:17:08.257 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:17:08.257 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:17:08.257 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:17:08.258 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:17:08.258 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:17:08.258 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:17:08.258 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:17:08.258 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:17:08.258 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First25
2024-11-06 02:17:08.259 | INFO     | app.crud.user:get_by_username_email_id:23 - Searching for user by email: firstUser25@gmail.com
2024-11-06 02:17:08.261 | INFO     | app.crud.user:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:17:08.261 | INFO     | app.crud.user:create:53 - Attempting to create user with username=First25, email=firstUser25@gmail.com
2024-11-06 02:17:08.267 | INFO     | app.crud.user:create:70 - User created successfully with username=First25, email=firstUser25@gmail.com
2024-11-06 02:17:08.267 | INFO     | app.services.user_service:create_user:33 - USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:18:18.065 | INFO     | app.services.user_service:create_user:11 - CREATING USER ACCOUNT
2024-11-06 02:18:18.065 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:18.066 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:18.066 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:18:18.066 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:18.067 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:18.067 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:18:18.067 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:18:18.067 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:18:18.067 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:18:18.068 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:18.068 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:18.068 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:18:18.068 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:18:18.068 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:18:18.068 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:18:18.069 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:18.069 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:18.069 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:18:18.091 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First25
2024-11-06 02:18:18.095 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First25
2024-11-06 02:18:18.096 | WARNING  | app.services.user_service:create_user:25 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:18:52.639 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:18:52.640 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:52.641 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:52.641 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:18:52.641 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:52.641 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:52.641 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:18:52.642 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:18:52.642 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:18:52.642 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:18:52.642 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:52.642 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:52.642 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:18:52.643 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:18:52.643 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:18:52.643 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:18:52.643 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:18:52.643 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:18:52.643 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:18:52.664 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First25
2024-11-06 02:18:52.669 | INFO     | app.crud.user:get_by_username_email_id:19 - User found by username: First25
2024-11-06 02:18:52.670 | WARNING  | app.services.user_service:create_user:25 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:19:07.948 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:19:07.949 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:19:07.949 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:19:07.949 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:19:07.949 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:19:07.950 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:19:07.950 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:19:07.950 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:19:07.950 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:19:07.950 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:19:07.951 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:19:07.951 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:19:07.951 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:19:07.951 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:19:07.951 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:19:07.952 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:19:07.952 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:19:07.952 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:19:07.952 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:19:07.952 | INFO     | app.crud.user:get_by_username_email_id:15 - Searching for user by username: First26
2024-11-06 02:19:07.953 | INFO     | app.crud.user:get_by_username_email_id:23 - Searching for user by email: firstUser26@gmail.com
2024-11-06 02:19:07.955 | INFO     | app.crud.user:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:19:07.955 | INFO     | app.crud.user:create:53 - Attempting to create user with username=First26, email=firstUser26@gmail.com
2024-11-06 02:19:07.960 | INFO     | app.crud.user:create:70 - User created successfully with username=First26, email=firstUser26@gmail.com
2024-11-06 02:19:07.960 | INFO     | app.services.user_service:create_user:33 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:22:13.898 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:22:13.899 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:13.900 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:13.900 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:22:13.901 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:13.901 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:13.901 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:22:13.901 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:22:13.902 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:22:13.902 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:22:13.902 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:13.902 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:13.902 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:22:13.903 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:22:13.903 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:22:13.903 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:22:13.903 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:13.903 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:13.903 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:22:13.925 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First26
2024-11-06 02:22:13.929 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First26
2024-11-06 02:22:13.930 | WARNING  | app.services.user_service:create_user:25 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:22:51.892 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:22:51.892 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:51.893 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:51.893 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:22:51.893 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:51.893 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:51.893 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:22:51.894 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:22:51.894 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:22:51.894 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:22:51.894 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:51.894 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:51.894 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:22:51.895 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:22:51.895 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:22:51.895 | INFO     | app.validators.user_validator:validate_role:87 - Validating user role
2024-11-06 02:22:51.895 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:22:51.895 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:22:51.895 | INFO     | app.validators.user_validator:validate_role:104 - User role validation passed
2024-11-06 02:22:51.895 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First27
2024-11-06 02:22:51.896 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser27@gmail.com
2024-11-06 02:22:51.898 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:22:51.898 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First27, email=firstUser27@gmail.com
2024-11-06 02:22:51.904 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First27, email=firstUser27@gmail.com
2024-11-06 02:22:51.904 | INFO     | app.services.user_service:create_user:33 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:23:36.853 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:23:36.855 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:23:36.855 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:23:36.856 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:23:36.856 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:23:36.857 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:23:36.857 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:23:36.857 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:23:36.857 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:23:36.859 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:23:36.859 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:23:36.860 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:23:36.860 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:23:36.860 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:23:36.862 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:23:36.862 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First28
2024-11-06 02:23:36.864 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser28@gmail.com
2024-11-06 02:23:36.865 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:23:36.865 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First28, email=firstUser28@gmail.com
2024-11-06 02:23:36.868 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First28, email=firstUser28@gmail.com
2024-11-06 02:23:36.868 | INFO     | app.services.user_service:create_user:33 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:24:35.755 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:24:35.756 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:24:35.757 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:24:35.757 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:24:35.757 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:24:35.758 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:24:35.758 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:24:35.758 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:24:35.759 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:24:35.759 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:24:35.759 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:24:35.759 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:24:35.760 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:24:35.760 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:24:35.760 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:24:35.780 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First29
2024-11-06 02:24:35.785 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser29@gmail.com
2024-11-06 02:24:35.787 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:24:35.787 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First29, email=firstUser29@gmail.com
2024-11-06 02:24:35.792 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First29, email=firstUser29@gmail.com
2024-11-06 02:24:35.792 | INFO     | app.services.user_service:create_user:34 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:25:45.888 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:25:45.889 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:45.890 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:45.890 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:25:45.891 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:45.891 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:45.891 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:25:45.892 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:25:45.892 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:25:45.893 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:25:45.893 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:45.893 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:45.893 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:25:45.893 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:25:45.894 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:25:45.894 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:25:45.916 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First30
2024-11-06 02:25:45.922 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser29@gmail.com
2024-11-06 02:25:45.924 | INFO     | app.crud.user_crud:get_by_username_email_id:27 - User found by email: firstUser29@gmail.com
2024-11-06 02:25:45.924 | WARNING  | app.services.user_service:create_user:28 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:25:57.824 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:25:57.825 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:57.825 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:57.825 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:25:57.826 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:57.826 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:57.826 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:25:57.826 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:25:57.826 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:25:57.826 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:25:57.826 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:25:57.827 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:25:57.827 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:25:57.827 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:25:57.827 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:25:57.827 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:25:57.828 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First30
2024-11-06 02:25:57.829 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser30@gmail.com
2024-11-06 02:25:57.829 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:25:57.830 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First30, email=firstUser30@gmail.com
2024-11-06 02:25:57.835 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First30, email=firstUser30@gmail.com
2024-11-06 02:25:57.835 | INFO     | app.services.user_service:create_user:36 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:28:34.486 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:28:34.487 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:28:34.487 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:28:34.487 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:28:34.488 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:28:34.488 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:28:34.488 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:28:34.488 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:28:34.488 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:28:34.488 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:28:34.489 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:28:34.489 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:28:34.489 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:28:34.489 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:28:34.489 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:28:34.489 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:28:34.512 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First30
2024-11-06 02:28:34.519 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First30
2024-11-06 02:28:34.519 | WARNING  | app.services.user_service:create_user:28 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:38:31.349 | INFO     | app.services.user_service:get_user_account_data:42 - 
GETTING USER ACCOUNT DATA
2024-11-06 02:38:31.350 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:38:31.351 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:38:31.372 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First10
2024-11-06 02:38:31.378 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First10
2024-11-06 02:38:31.378 | INFO     | app.services.user_service:get_user_account_data:50 - 
USER ACCOUNT DATA HAS BEEN PARSED
2024-11-06 02:39:23.341 | INFO     | app.services.user_service:get_user_account_data:42 - 
GETTING USER ACCOUNT DATA
2024-11-06 02:39:23.341 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:39:23.342 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:39:23.364 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First10
2024-11-06 02:39:23.374 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First10
2024-11-06 02:39:23.374 | INFO     | app.services.user_service:get_user_account_data:50 - 
USER ACCOUNT DATA HAS BEEN PARSED
2024-11-06 02:48:40.138 | INFO     | app.services.user_service:get_user_account_data:43 - 
GETTING USER ACCOUNT DATA
2024-11-06 02:48:40.138 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:48:40.139 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:48:40.160 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First108
2024-11-06 02:48:40.165 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:48:40.165 | WARNING  | app.services.user_service:get_user_account_data:48 - 
CANNOT GET USER ACCOUNT DATA - USER NOT FOUND
2024-11-06 02:50:03.317 | INFO     | app.services.user_service:get_user_account_data:43 - 
GETTING USER ACCOUNT DATA
2024-11-06 02:50:03.318 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:50:03.318 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:50:03.339 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First108
2024-11-06 02:50:03.343 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:50:03.344 | WARNING  | app.services.user_service:get_user_account_data:48 - 
CANNOT GET USER ACCOUNT DATA - USER: First108 HAS NOT BEEN FOUND
2024-11-06 02:51:00.026 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:51:00.029 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:00.029 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:00.029 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:51:00.030 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:00.030 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:00.030 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:51:00.030 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:51:00.031 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:51:00.031 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:51:00.031 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:00.032 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:00.032 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:51:00.032 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:51:00.032 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:51:00.033 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:51:00.033 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First30
2024-11-06 02:51:00.037 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First30
2024-11-06 02:51:00.037 | WARNING  | app.services.user_service:create_user:28 - 
USER ACCOUNT CANNOT BE CREATED AS THERE IS AN EXISTING USER WITH THE SAME USERNAME OR EMAIL
2024-11-06 02:51:10.212 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:51:10.212 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:10.212 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:10.213 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:51:10.213 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:10.213 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:10.213 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:51:10.213 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:51:10.214 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:51:10.214 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:51:10.214 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:10.214 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:10.214 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:51:10.214 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:51:10.214 | WARNING  | app.validators.user_validator:validate_password:68 - Provided password is too short
2024-11-06 02:51:35.570 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:51:35.571 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:35.571 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:35.572 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:51:35.572 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:35.572 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:35.572 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:51:35.573 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:51:35.573 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:51:35.573 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:51:35.573 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:35.573 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:35.574 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:51:35.574 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:51:35.574 | WARNING  | app.validators.user_validator:validate_password:72 - Password must contain at least one uppercase letter
2024-11-06 02:51:47.638 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:51:47.639 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:47.639 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:47.640 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:51:47.640 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:47.640 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:47.640 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:51:47.640 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:51:47.641 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:51:47.641 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:51:47.641 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:47.641 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:47.641 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:51:47.641 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:51:47.641 | WARNING  | app.validators.user_validator:validate_password:76 - Password must contain at least one number
2024-11-06 02:51:53.106 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:51:53.107 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:53.108 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:53.108 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:51:53.108 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:53.108 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:53.108 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:51:53.109 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:51:53.109 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:51:53.109 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:51:53.109 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:51:53.109 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:51:53.110 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:51:53.110 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:51:53.110 | WARNING  | app.validators.user_validator:validate_password:80 - Password must contain at least one special character
2024-11-06 02:52:01.436 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:52:01.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:01.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:01.437 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:52:01.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:01.437 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:01.438 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:52:01.438 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:52:01.438 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:52:01.438 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:52:01.438 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:01.439 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:01.439 | WARNING  | app.validators.user_validator:validate_email:50 - Provided email is invalid: firstUser31@gm@ail.com
2024-11-06 02:52:06.594 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:52:06.595 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:06.595 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:06.595 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:52:06.596 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:06.596 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:06.596 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:52:06.596 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:52:06.596 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:52:06.597 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:52:06.597 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:52:06.597 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:52:06.597 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:52:06.597 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:52:06.597 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:52:06.597 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:52:06.598 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First31
2024-11-06 02:52:06.599 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser31@gmail..com
2024-11-06 02:52:06.600 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:52:06.600 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First31, email=firstUser31@gmail..com
2024-11-06 02:52:06.606 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First31, email=firstUser31@gmail..com
2024-11-06 02:52:06.606 | INFO     | app.services.user_service:create_user:36 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:54:27.498 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:54:27.499 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:27.500 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:27.500 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:54:27.500 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:27.500 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:27.500 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:54:27.501 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:54:27.501 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:54:27.501 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:54:27.501 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:27.501 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:27.502 | WARNING  | app.validators.user_validator:validate_email:50 - Provided email is invalid: firstUser32@gmail..com
2024-11-06 02:54:39.210 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:54:39.211 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:39.211 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:39.211 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:54:39.212 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:39.212 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:39.212 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:54:39.212 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:54:39.212 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:54:39.212 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:54:39.213 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:39.213 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:39.213 | WARNING  | app.validators.user_validator:validate_email:50 - Provided email is invalid: firstU@ser32@gmail.com
2024-11-06 02:54:48.366 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:54:48.367 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:48.367 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:48.367 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:54:48.367 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:48.367 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:48.368 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:54:48.368 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:54:48.368 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:54:48.368 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:54:48.368 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:54:48.368 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:54:48.369 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:54:48.369 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:54:48.369 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:54:48.369 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:54:48.392 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First32
2024-11-06 02:54:48.397 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: 2@gmail.com
2024-11-06 02:54:48.399 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:54:48.399 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First32, email=2@gmail.com
2024-11-06 02:54:48.404 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First32, email=2@gmail.com
2024-11-06 02:54:48.404 | INFO     | app.services.user_service:create_user:36 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:56:06.893 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:56:06.894 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:06.894 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:06.894 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:56:06.896 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:06.896 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:06.897 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:56:06.897 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:56:06.897 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:56:06.897 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:56:06.897 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:06.897 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:06.898 | WARNING  | app.validators.user_validator:validate_email:45 - Email length out of bounds, provided email: 2@gm
2024-11-06 02:56:31.792 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:56:31.793 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:31.793 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:31.794 | INFO     | app.validators.user_validator:validate_username:16 - Validating username format
2024-11-06 02:56:31.794 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:31.794 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:31.794 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:56:31.795 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:56:31.795 | INFO     | app.validators.user_validator:validate_username:30 - Username validation passed
2024-11-06 02:56:31.795 | INFO     | app.validators.user_validator:validate_email:38 - Validating email format
2024-11-06 02:56:31.795 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:56:31.795 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:56:31.795 | INFO     | app.validators.user_validator:validate_email:53 - Email validation passed
2024-11-06 02:56:31.796 | INFO     | app.validators.user_validator:validate_password:61 - Validating password format
2024-11-06 02:56:31.796 | INFO     | app.validators.user_validator:validate_password:82 - Password validation passed
2024-11-06 02:56:31.796 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:56:31.796 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First33
2024-11-06 02:56:31.797 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser33@gmail.com
2024-11-06 02:56:31.798 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:56:31.798 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First33, email=firstUser33@gmail.com
2024-11-06 02:56:31.804 | ERROR    | app.crud.user_crud:create:77 - Exception with username=First33, email=firstUser33@gmail.com, role:UserRole.registered_user: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)

[SQL: INSERT INTO "user" (username, email, password_hash, role) VALUES (%(username)s, %(email)s, %(password_hash)s, %(role)s) RETURNING "user".user_id, "user".created_at]
[parameters: {'username': 'First33', 'email': 'firstUser33@gmail.com', 'password_hash': 'Password1234$ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss', 'role': 'registered_user'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000002C6EAE8C400>
    │    └ <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x000002C6EB254850>
    └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'username': 'First33', 'email': 'firstUser33@gmail.com', 'password_hash': 'Password1234$ssssssssssssssssssssssssssssssssssss...
    │      │       └ 'INSERT INTO "user" (username, email, password_hash, role) VALUES (%(username)s, %(email)s, %(password_hash)s, %(role)s) RETU...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x000002C6ECA5CC80; closed: -1>

psycopg2.errors.StringDataRightTruncation: value too long for type character varying(255)



The above exception was the direct cause of the following exception:


Traceback (most recent call last):

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x000002C6E7104860>
    └ <WorkerThread(AnyIO worker thread, started 9532)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    │    └ <function WorkerThread.run at 0x000002C6EC5C7B00>
    └ <WorkerThread(AnyIO worker thread, started 9532)>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 914, in run
    result = context.run(func, *args)
             │       │   │      └ ()
             │       │   └ functools.partial(<function create_user at 0x000002C6EC579300>, db=<sqlalchemy.orm.session.Session object at 0x000002C6EC5BB3...
             │       └ <method 'run' of '_contextvars.Context' objects>
             └ <_contextvars.Context object at 0x000002C6EB57BF00>

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\main.py", line 37, in create_user
    return user_services.create_user(db=db, user=user)
           │             │              │        └ UserCreate(username='First33', email='firstUser33@gmail.com', password='Password1234$ssssssssssssssssssssssssssssssssssssssss...
           │             │              └ <sqlalchemy.orm.session.Session object at 0x000002C6EC5BB310>
           │             └ <function create_user at 0x000002C6EB56D760>
           └ <module 'app.services.user_service' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\service...

  File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\services\user_service.py", line 33, in create_user
    user = user_crud.create(db=db, user=user)
           │         │         │        └ UserCreate(username='First33', email='firstUser33@gmail.com', password='Password1234$ssssssssssssssssssssssssssssssssssssssss...
           │         │         └ <sqlalchemy.orm.session.Session object at 0x000002C6EC5BB310>
           │         └ <function create at 0x000002C6EB56DE40>
           └ <module 'app.crud.user_crud' from 'C:\\Users\\tomas\\Documents\\Saityno Progr. Projektavimas\\StreamaBit\\app\\crud\\user_cru...

> File "C:\Users\tomas\Documents\Saityno Progr. Projektavimas\StreamaBit\app\crud\user_crud.py", line 68, in create
    db.commit()
    │  └ <function Session.commit at 0x000002C6EB151A80>
    └ <sqlalchemy.orm.session.Session object at 0x000002C6EC5BB310>

  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 2028, in commit
    trans.commit(_to_root=True)
    │     └ <function SessionTransaction.commit at 0x000002C6EB150B80>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000002C6EC5964E0>
  File "<string>", line 2, in commit
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {'_to_root': True}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000002C6EC5964E0>
                └ <function SessionTransaction.commit at 0x000002C6EB1509A0>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1313, in commit
    self._prepare_impl()
    │    └ <function SessionTransaction._prepare_impl at 0x000002C6EB150860>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000002C6EC5964E0>
  File "<string>", line 2, in _prepare_impl
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                │  │      │      └ {}
                │  │      └ ()
                │  └ <sqlalchemy.orm.session.SessionTransaction object at 0x000002C6EC5964E0>
                └ <function SessionTransaction._prepare_impl at 0x000002C6EB1507C0>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 1288, in _prepare_impl
    self.session.flush()
    │    │       └ <function Session.flush at 0x000002C6EB1609A0>
    │    └ <sqlalchemy.orm.session.Session object at 0x000002C6EC5BB310>
    └ <sqlalchemy.orm.session.SessionTransaction object at 0x000002C6EC5964E0>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4352, in flush
    self._flush(objects)
    │    │      └ None
    │    └ <function Session._flush at 0x000002C6EB160B80>
    └ <sqlalchemy.orm.session.Session object at 0x000002C6EC5BB310>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4487, in _flush
    with util.safe_reraise():
         │    └ <class 'sqlalchemy.util.langhelpers.safe_reraise'>
         └ <module 'sqlalchemy.util' from 'C:\\Users\\tomas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy...
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
          │         │              └ <traceback object at 0x000002C6ECA6B380>
          │         └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)\n')
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\session.py", line 4448, in _flush
    flush_context.execute()
    │             └ <function UOWTransaction.execute at 0x000002C6EB149440>
    └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000002C6ECA57AD0>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 466, in execute
    rec.execute(self)
    │   │       └ <sqlalchemy.orm.unitofwork.UOWTransaction object at 0x000002C6ECA57AD0>
    │   └ <function SaveUpdateAll.execute at 0x000002C6EB149F80>
    └ SaveUpdateAll(Mapper[User(user)])
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
    │    │         │               └ <function save_obj at 0x000002C6EB0F5B20>
    │    │         └ <module 'sqlalchemy.orm.persistence' from 'C:\\Users\\tomas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\...
    │    └ <module 'sqlalchemy.util.preloaded' from 'C:\\Users\\tomas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\...
    └ <module 'sqlalchemy.util' from 'C:\\Users\\tomas\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\sqlalchemy...
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 93, in save_obj
    _emit_insert_statements(
    └ <function _emit_insert_statements at 0x000002C6EB140220>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\orm\persistence.py", line 1233, in _emit_insert_statements
    result = connection.execute(
             │          └ <function Connection.execute at 0x000002C6EADC8400>
             └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1418, in execute
    return meth(
           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.dml.Insert object at 0x000002C6ECA6AC50>>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\sql\elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           │          └ <function Connection._execute_clauseelement at 0x000002C6EADC8720>
           └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          │    └ <function Connection._execute_context at 0x000002C6EADC8900>
          └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1846, in _execute_context
    return self._exec_single_context(
           │    └ <function Connection._exec_single_context at 0x000002C6EADC89A0>
           └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
    │    └ <function Connection._handle_dbapi_exception at 0x000002C6EADC8C20>
    └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
          │                    │              │                 └ StringDataRightTruncation('value too long for type character varying(255)\n')
          │                    │              └ (<class 'psycopg2.errors.StringDataRightTruncation'>, StringDataRightTruncation('value too long for type character varying(25...
          │                    └ <method 'with_traceback' of 'BaseException' objects>
          └ DataError('(psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)\n')
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
    │    │       └ <function DefaultDialect.do_execute at 0x000002C6EAE8C400>
    │    └ <sqlalchemy.dialects.postgresql.psycopg2.PGDialect_psycopg2 object at 0x000002C6EB254850>
    └ <sqlalchemy.engine.base.Connection object at 0x000002C6ECA6A710>
  File "C:\Users\tomas\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
    │      │       │          └ {'username': 'First33', 'email': 'firstUser33@gmail.com', 'password_hash': 'Password1234$ssssssssssssssssssssssssssssssssssss...
    │      │       └ 'INSERT INTO "user" (username, email, password_hash, role) VALUES (%(username)s, %(email)s, %(password_hash)s, %(role)s) RETU...
    │      └ <method 'execute' of 'psycopg2.extensions.cursor' objects>
    └ <cursor object at 0x000002C6ECA5CC80; closed: -1>

sqlalchemy.exc.DataError: (psycopg2.errors.StringDataRightTruncation) value too long for type character varying(255)

[SQL: INSERT INTO "user" (username, email, password_hash, role) VALUES (%(username)s, %(email)s, %(password_hash)s, %(role)s) RETURNING "user".user_id, "user".created_at]
[parameters: {'username': 'First33', 'email': 'firstUser33@gmail.com', 'password_hash': 'Password1234$ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss', 'role': 'registered_user'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
2024-11-06 02:59:00.589 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:59:00.590 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:00.590 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:00.591 | INFO     | app.validators.user_validator:validate_username:17 - Validating username format
2024-11-06 02:59:00.591 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:00.591 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:00.591 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:59:00.591 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:59:00.592 | INFO     | app.validators.user_validator:validate_username:31 - Username validation passed
2024-11-06 02:59:00.592 | INFO     | app.validators.user_validator:validate_email:39 - Validating email format
2024-11-06 02:59:00.592 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:00.592 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:00.592 | INFO     | app.validators.user_validator:validate_email:54 - Email validation passed
2024-11-06 02:59:00.593 | INFO     | app.validators.user_validator:validate_password:62 - Validating password format
2024-11-06 02:59:00.593 | WARNING  | app.validators.user_validator:validate_password:75 - Provided password is too long
2024-11-06 02:59:16.194 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:59:16.194 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:16.194 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:16.195 | INFO     | app.validators.user_validator:validate_username:17 - Validating username format
2024-11-06 02:59:16.195 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:16.195 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:16.195 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:59:16.195 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:59:16.196 | INFO     | app.validators.user_validator:validate_username:31 - Username validation passed
2024-11-06 02:59:16.196 | INFO     | app.validators.user_validator:validate_email:39 - Validating email format
2024-11-06 02:59:16.196 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:16.196 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:16.196 | INFO     | app.validators.user_validator:validate_email:54 - Email validation passed
2024-11-06 02:59:16.196 | INFO     | app.validators.user_validator:validate_password:62 - Validating password format
2024-11-06 02:59:16.197 | INFO     | app.validators.user_validator:validate_password:89 - Password validation passed
2024-11-06 02:59:16.197 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 02:59:16.219 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First33
2024-11-06 02:59:16.224 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser33@gmail.com
2024-11-06 02:59:16.225 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 02:59:16.225 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First33, email=firstUser33@gmail.com
2024-11-06 02:59:16.234 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First33, email=firstUser33@gmail.com
2024-11-06 02:59:16.235 | INFO     | app.services.user_service:create_user:36 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 02:59:55.960 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 02:59:55.961 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:55.961 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:55.961 | INFO     | app.validators.user_validator:validate_username:17 - Validating username format
2024-11-06 02:59:55.961 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:55.961 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:55.962 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 02:59:55.962 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 02:59:55.962 | INFO     | app.validators.user_validator:validate_username:31 - Username validation passed
2024-11-06 02:59:55.962 | INFO     | app.validators.user_validator:validate_email:39 - Validating email format
2024-11-06 02:59:55.962 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 02:59:55.963 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 02:59:55.963 | INFO     | app.validators.user_validator:validate_email:54 - Email validation passed
2024-11-06 02:59:55.963 | INFO     | app.validators.user_validator:validate_password:62 - Validating password format
2024-11-06 02:59:55.963 | WARNING  | app.validators.user_validator:validate_password:71 - Provided password is too short
2024-11-06 03:00:03.653 | INFO     | app.services.user_service:create_user:11 - 
CREATING USER ACCOUNT
2024-11-06 03:00:03.654 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 03:00:03.654 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 03:00:03.654 | INFO     | app.validators.user_validator:validate_username:17 - Validating username format
2024-11-06 03:00:03.655 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 03:00:03.655 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 03:00:03.655 | INFO     | app.validators.shared_validator:letters_numbers_only:17 - Validating input
2024-11-06 03:00:03.655 | INFO     | app.validators.shared_validator:letters_numbers_only:23 - Input passed validation
2024-11-06 03:00:03.655 | INFO     | app.validators.user_validator:validate_username:31 - Username validation passed
2024-11-06 03:00:03.655 | INFO     | app.validators.user_validator:validate_email:39 - Validating email format
2024-11-06 03:00:03.656 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 03:00:03.656 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 03:00:03.656 | INFO     | app.validators.user_validator:validate_email:54 - Email validation passed
2024-11-06 03:00:03.656 | INFO     | app.validators.user_validator:validate_password:62 - Validating password format
2024-11-06 03:00:03.656 | INFO     | app.validators.user_validator:validate_password:89 - Password validation passed
2024-11-06 03:00:03.656 | INFO     | app.services.user_service:create_user:21 - Got empty user role, proceeding further
2024-11-06 03:00:03.657 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First34
2024-11-06 03:00:03.658 | INFO     | app.crud.user_crud:get_by_username_email_id:23 - Searching for user by email: firstUser34@gmail.com
2024-11-06 03:00:03.659 | INFO     | app.crud.user_crud:get_by_username_email_id:38 - User not found with given parameters
2024-11-06 03:00:03.659 | INFO     | app.crud.user_crud:create:53 - Attempting to create user with username=First34, email=firstUser34@gmail.com
2024-11-06 03:00:03.662 | INFO     | app.crud.user_crud:create:70 - User created successfully with username=First34, email=firstUser34@gmail.com
2024-11-06 03:00:03.662 | INFO     | app.services.user_service:create_user:36 - 
USER ACCOUNT HAS BEEN CREATED
2024-11-06 03:00:16.045 | INFO     | app.services.user_service:get_user_account_data:43 - 
GETTING USER ACCOUNT DATA
2024-11-06 03:00:16.045 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:29 - Validating input
2024-11-06 03:00:16.045 | INFO     | app.validators.shared_validator:validate_sql_malicious_input:60 - Input passed validation
2024-11-06 03:00:16.046 | INFO     | app.crud.user_crud:get_by_username_email_id:15 - Searching for user by username: First33
2024-11-06 03:00:16.047 | INFO     | app.crud.user_crud:get_by_username_email_id:19 - User found by username: First33
2024-11-06 03:00:16.047 | INFO     | app.services.user_service:get_user_account_data:51 - 
USER ACCOUNT DATA HAS BEEN PARSED
